spring:
  application:
    name: TEAM5-BOOK-SERVER  # 👈 application 바로 아래, 띄어쓰기 2칸 또는 4칸

  config:
    import: "optional:configserver:"
    enabled: false  # Config Server 끄기 (로컬 실행용)

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/